name: Train Model & Deploy Locally

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AKI }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SAK }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Print all environment variables
        run: printenv

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AKI }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SAK }}
        run: echo "AWS credentials configured"

      - name: Print AWS credentials environment variables
        run: |
          echo "AWS_ACCESS_KEY_ID: ${{ secrets.AKI }}"
          echo "AWS_SECRET_ACCESS_KEY: ${{ secrets.SAK }}"
                
      - name: Print all environment variables
        run: printenv

      - name: Get Data from S3
        run: python property_friends_real_state/modeling/get_data.py

      - name: Train Model
        run: python property_friends_real_state/modeling/train.py

      - name: Install Docker Compose
        run: |
          sudo apt update
          sudo apt install -y docker-compose

      - name: Build and run FastAPI container
        run: |
          docker-compose up -d --build

      - name: Check if FastAPI is running
        run: |
          sleep 5
          curl -f http://localhost:8000 || (echo "FastAPI did not start" && exit 1)